
[package]
name = 'problem_sample'
version = '1.0.0'


[addresses]
problem_sample = "0x1"
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework"}
